CONJOINT PLAN='G:medicine_plan.sav'
    /DATA='G:medicine_prefs.sav'
    /SEQUENCE=PREF1 TO PREF22
    /SUBJECT=ID
    /FACTORS=SAFETY EFFICACY (LINEAR MORE) 
     PRICE (LINEAR LESS)
     PILLSIZE PROLONGEDACTIVITY (DISCRETE)
    /PRINT=SUMMARYONLY.